INSERT INTO products (
    name,
    slug,
    description,
    category,
    season,
    fabric,
    color,
    size_label,
    price,
    compare_at_price,
    stock,
    image_url,
    is_active
) VALUES
(
    'Conjunto Studio Sculpt Preto',
    'conjunto-studio-sculpt-preto',
    'Top e legging de alta sustentacao para treino de forca, yoga e rotina urbana com acabamento elegante.',
    'fitness-feminino',
    'inverno',
    'poliamida compressiva',
    'Preto',
    'P/M/G/GG',
    249.90,
    299.90,
    28,
    'https://images.pexels.com/photos/6516177/pexels-photo-6516177.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
),
(
    'Set Flow Pastel Pilates',
    'set-flow-pastel-pilates',
    'Conjunto em tons suaves com toque macio, ideal para pilates, alongamento e treinos de baixo impacto.',
    'fitness-feminino',
    'primavera',
    'malha premium respiravel',
    'Rosa pastel',
    'P/M/G',
    219.90,
    259.90,
    20,
    'https://images.pexels.com/photos/8483394/pexels-photo-8483394.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
),
(
    'Conjunto Gray Power Studio',
    'conjunto-gray-power-studio',
    'Top esportivo e legging em tom grafite, com visual de estudio e sustentacao para treino intenso.',
    'fitness-feminino',
    'verao',
    'dry fit estruturado',
    'Grafite',
    'P/M/G',
    109.90,
    139.90,
    35,
    'https://images.pexels.com/photos/6311389/pexels-photo-6311389.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
),
(
    'Conjunto Outdoor Energy Azul',
    'conjunto-outdoor-energy-azul',
    'Top e legging azul para treino ao ar livre, com caimento firme e visual vibrante.',
    'fitness-feminino',
    'verao',
    'suplex leve',
    'Azul',
    'P/M/G/GG',
    149.90,
    179.90,
    26,
    'https://images.pexels.com/photos/29242373/pexels-photo-29242373.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
),
(
    'Macacao Balance Soft',
    'macacao-balance-soft',
    'Macacao fitness de toque suave para treino, danca e composicoes casuais com visual limpo.',
    'fitness-feminino',
    'outono',
    'microfibra elastica',
    'Areia',
    'P/M/G',
    189.90,
    229.90,
    18,
    'https://images.pexels.com/photos/5770475/pexels-photo-5770475.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
),
(
    'Short Studio Cycling Preto',
    'short-studio-cycling-preto',
    'Short cycling preto com top coordenado para danca, funcional e treinos dinamicos em estudio.',
    'fitness-feminino',
    'primavera',
    'tecido leve com elastano',
    'Preto',
    'P/M/G',
    99.90,
    129.90,
    32,
    'https://images.pexels.com/photos/6516171/pexels-photo-6516171.jpeg?auto=compress&cs=tinysrgb&w=1200',
    TRUE
)
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    season = EXCLUDED.season,
    fabric = EXCLUDED.fabric,
    color = EXCLUDED.color,
    size_label = EXCLUDED.size_label,
    price = EXCLUDED.price,
    compare_at_price = EXCLUDED.compare_at_price,
    stock = EXCLUDED.stock,
    image_url = EXCLUDED.image_url,
    is_active = TRUE,
    updated_at = NOW();
